<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_length" value="0.30"/>
    <xacro:property name="chassis_width" value="0.20"/>
    <xacro:property name="chassis_height" value="0.01"/>
    <xacro:property name="upper_layer_height" value="0.01"/>
    <xacro:property name="layer_gap" value="0.10"/>
    <xacro:property name="land_to_bottom" value="0.04"/>
    <xacro:property name="total_height" value="0.21"/>
    <xacro:property name="battery_length" value="0.145"/>
    <xacro:property name="battery_width" value="0.04"/>
    <xacro:property name="battery_height" value="0.075"/>
    <xacro:property name="battery_mass" value="0.7"/>
    <xacro:property name="wheel_radius" value="0.04"/>
    <xacro:property name="wheel_thickness" value="0.037"/>
    <xacro:property name="wheel_mass" value="0.095"/>
    <xacro:property name="wheel_offset_x" value="0.05"/>
    <xacro:property name="wheel_offset_y" value="0.10"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- Bottom Layer -->
    <link name="bottom_layer">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${land_to_bottom + chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${land_to_bottom + chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${land_to_bottom + chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    
 <gazebo reference="bottom_layer">
  <material>Gazebo/orange</material>
</gazebo>


  
    <!-- Upper Layer -->
    <joint name="upper_layer_joint" type="fixed">
        <parent link="bottom_layer"/>
        <child link="upper_layer"/>
        <origin xyz="0 0 ${layer_gap}" rpy="0 0 0"/>
    </joint>
    <link name="upper_layer">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${upper_layer_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${upper_layer_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${upper_layer_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${upper_layer_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${upper_layer_height}">
            <origin xyz="${chassis_length/2} 0 ${upper_layer_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
     <gazebo reference="upper_layer">
  <material>Gazebo/Orange</material>
</gazebo>


    <!-- Battery -->
    <joint name="battery_joint" type="fixed">
        <parent link="bottom_layer"/>
        <child link="battery"/>
        <origin xyz="${(chassis_length-battery_length)/2} 0 ${layer_gap-battery_height-0.02}" rpy="0 0 0"/>
    </joint>
    <link name="battery">
        <visual>
            <origin xyz="${battery_length/2} 0 ${battery_height/2}"/>
            <geometry>
                <box size="${battery_length} ${battery_width} ${battery_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="${battery_length/2} 0 ${battery_height/2}"/>
            <geometry>
                <box size="${battery_length} ${battery_width} ${battery_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${battery_mass}" x="${battery_length}" y="${battery_width}" z="${battery_height}">
            <origin xyz="${battery_length/2} 0 ${battery_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
     <gazebo reference="battery">
  <material>Gazebo/Yellow</material>
</gazebo>


    <!-- 4 Wheels -->
    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="bottom_layer"/>
        <child link="front_left_wheel"/>
        <origin xyz="0.02 ${wheel_offset_y} 0" rpy="-1.5708 0 0" />
        <axis xyz="0 0 1"/>
    </joint>
    <link name="front_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="bottom_layer"/>
        <child link="front_right_wheel"/>
        <origin xyz="0.02 -${wheel_offset_y} 0" rpy="1.5708 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>
    <link name="front_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="bottom_layer"/>
        <child link="rear_left_wheel"/>
        <origin xyz="0.26 ${wheel_offset_y} 0" rpy="-1.5708 0 0" />
        <axis xyz="0 0 1"/>
    </joint>
    <link name="rear_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="bottom_layer"/>
        <child link="rear_right_wheel"/>
        <origin xyz="0.26 -${wheel_offset_y} 0" rpy="1.5708 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>
    <link name="rear_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Threaded Rods (Spacers) -->
    <xacro:property name="rod_radius" value="0.005"/>
    <xacro:property name="rod_height" value="${layer_gap}"/>
    <!-- Front Left Rod -->
    <joint name="rod_fl_joint" type="fixed">
        <parent link="bottom_layer"/>
        <child link="rod_fl"/>
        <origin xyz="0.01 0.09 0" rpy="0 0 0"/>
    </joint>
    <link name="rod_fl">
        <visual>
            <origin xyz="0 0 ${rod_height/2}"/>
            <geometry>
                <cylinder radius="${rod_radius}" length="${rod_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
    </link>
    <!-- Front Right Rod -->
    <joint name="rod_fr_joint" type="fixed">
        <parent link="bottom_layer"/>
        <child link="rod_fr"/>
        <origin xyz="0.01 -0.09 0" rpy="0 0 0"/>
    </joint>
    <link name="rod_fr">
        <visual>
            <origin xyz="0 0 ${rod_height/2}"/>
            <geometry>
                <cylinder radius="${rod_radius}" length="${rod_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
    </link>
    <!-- Rear Left Rod -->
    <joint name="rod_rl_joint" type="fixed">
        <parent link="bottom_layer"/>
        <child link="rod_rl"/>
        <origin xyz="0.29 0.09 0" rpy="0 0 0"/>
    </joint>
    <link name="rod_rl">
        <visual>
            <origin xyz="0 0 ${rod_height/2}"/>
            <geometry>
                <cylinder radius="${rod_radius}" length="${rod_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
    </link>
    <!-- Rear Right Rod -->
    <joint name="rod_rr_joint" type="fixed">
        <parent link="bottom_layer"/>
        <child link="rod_rr"/>
        <origin xyz="0.29 -0.09 0" rpy="0 0 0"/>
    </joint>
    <link name="rod_rr">
        <visual>
            <origin xyz="0 0 ${rod_height/2}"/>
            <geometry>
                <cylinder radius="${rod_radius}" length="${rod_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
    </link>

    <!-- Connect bottom_layer to base_link -->
    <joint name="bottom_layer_joint" type="fixed">
        <parent link="base_link"/>
        <child link="bottom_layer"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

</robot>
